// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/audit-logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit-logs">> = Specific
  const handler = {} as typeof import("../../src/app/audit-logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/authority-dashboard/audit-history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/authority-dashboard/audit-history">> = Specific
  const handler = {} as typeof import("../../src/app/authority-dashboard/audit-history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/authority-dashboard/evidence-review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/authority-dashboard/evidence-review">> = Specific
  const handler = {} as typeof import("../../src/app/authority-dashboard/evidence-review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/authority-dashboard/incoming-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/authority-dashboard/incoming-requests">> = Specific
  const handler = {} as typeof import("../../src/app/authority-dashboard/incoming-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/authority-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/authority-dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/authority-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/examination-database/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/examination-database">> = Specific
  const handler = {} as typeof import("../../src/app/examination-database/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/human-review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/human-review">> = Specific
  const handler = {} as typeof import("../../src/app/human-review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/my-reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my-reports">> = Specific
  const handler = {} as typeof import("../../src/app/my-reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/submissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/submissions">> = Specific
  const handler = {} as typeof import("../../src/app/submissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/upload-ingest/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/upload-ingest">> = Specific
  const handler = {} as typeof import("../../src/app/upload-ingest/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
